language: node_js
node_js:
- "4"
- "6"
install:
- npm install
script:
- npm run lint
- npm run coverage
notifications:
  slack:
    rooms:
      secure: EhlwiP7uIQ7xD/MqWbnmqDmGC8JRtXpJH9XsaWfKJ9hfrNdK8MPNz5Rjz6+z8T6f68mwS1VOpcyGJlSjFwdYmPOslpGuc7QvLUda5bXTNuUvCtc90GRd2BOyDi5zHOvuOTPiRCNjp8shEmDkGln8SQa2B04Oeiwrx/XfdnTtfAxLFGZCTsHkudb9pnopRbpBdgaJ9Pg5c1Y+xvj1X9rQAy3+9+sf+jr7JgAKLpiijVVUPHpMKO1lyoM9b7pK8V5EJhN2YjlbH9TbL+PS71++N0KCDLdh803lpq3j4engG1liGKJxoFbbuHBuVBF8gVhzjsihe8o9RnChPFqP8vvh9O3RXMdOvfv2EamrO5yvB+9N7xn0FxKxdAcWvCBwPvyDUUEhBNOw8E3T99WSFO50Gfb8jMPQDD5rDF78YCSKcePKi/de2lYmZNo52MlJU4nwb+iDJUyacnX82O/Nmen9Yc/nUV37SBhV8yBBI+VOknRltDGt6ZABEpNEUev9DOr1BBJCT18Q8hFKnu4q/B9fuoa5YWbyfLl5wJowQYrX+5JCQMN93/loze+KGiMJFk0Iw+PXXDQzRk8bgeGjHTbK7i0l7W6oN+ouP2JIrSfviJ9lNnSw8E7qNVBCdmtmnPni/h+7Q+caOPd1YgYDvtCXvLWvkFZ3WHatbE8LvxdCIA4=
    on_success: change
    on_failure: always
  email: false
